import type { LevelDef } from "../types";

// Waves enter about 5 s apart at 1 px a frame; they must be sorted by `at`.
export const LEVELS: LevelDef[] = [
  {
    terrain: { seed: 1984, blocks: { plaza: 0.6, rubble: 0 } },
    waves: [
      { at: 60, kind: "straight", count: 3, x: 120, spacing: 120 },
      { at: 360, kind: "sine", count: 4, x: 90, spacing: 100 },
      { at: 660, kind: "straight", count: 5, x: 60, spacing: 90 },
      { at: 960, kind: "bomber", count: 1, x: 240, spacing: 0 },
      { at: 1260, kind: "sine", count: 5, x: 80, spacing: 80 },
      { at: 1560, kind: "straight", count: 3, x: 300, spacing: 60 },
      { at: 1680, kind: "straight", count: 3, x: 60, spacing: 60 },
      { at: 1980, kind: "bomber", count: 2, x: 140, spacing: 200 },
      { at: 2280, kind: "sine", count: 6, x: 65, spacing: 70 },
      { at: 2580, kind: "bomber", count: 1, x: 240, spacing: 0 },
      { at: 2640, kind: "straight", count: 2, x: 120, spacing: 240 },
    ],
    // Few and slow-sweeping: level 1 teaches what a cone is before it punishes.
    eyes: [
      {
        type: "tower",
        at: 450,
        on: "rooftop",
        facing: 135,
        range: 170,
        sweepAmp: 35,
        sweepSpeed: 0.03,
      },
      {
        type: "tower",
        at: 900,
        on: "plaza",
        facing: 45,
        range: 180,
        sweepAmp: 30,
        sweepSpeed: 0.025,
      },
      {
        type: "drone",
        at: 1100,
        x: 240,
        path: "patrol",
        facing: 90,
        range: 150,
        sweepAmp: 25,
        sweepSpeed: 0.04,
      },
      {
        type: "tower",
        at: 1500,
        on: "street",
        facing: 90,
        range: 160,
        sweepAmp: 50,
        sweepSpeed: 0.03,
      },
      {
        type: "tower",
        at: 2100,
        on: "rooftop",
        facing: -45,
        range: 200,
        sweepAmp: 30,
        sweepSpeed: 0.02,
      },
      {
        type: "drone",
        at: 2300,
        x: 360,
        path: "sine",
        facing: 90,
        range: 140,
        sweepAmp: 20,
        sweepSpeed: 0.05,
      },
    ],
  },
];
